name: CI - qr_code (Docker build)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
  packages: write
  
jobs:
  build-backend-and-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # (Tùy chọn) Cài Node để chạy test nếu bạn có test
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Backend dependency sanity check
        run: |
          cd backend
          npm ci
          node -e "require('express'); require('swagger-ui-express'); require('yamljs')"

      - name: Install root deps & run tests (optional)
        run: |
          if [ -f package.json ]; then
            npm ci || true
            npm test --if-present || true
          fi

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/qr_code-backend:latest
            ghcr.io/${{ env.OWNER_LC }}/qr_code-backend:${{ github.sha }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/qr_code-frontend:latest
            ghcr.io/${{ env.OWNER_LC }}/qr_code-frontend:${{ github.sha }}
